import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const poppins = Poppins({
    subsets: ['latin'],
    weight: ["400", "500", "600", "700"],
    variable: "--font-poppins"
})

export const metadata: Metadata = {
    title: "Evently - Your Personal Event Manager",
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={poppins.variable}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
